#ifndef CODEGEN_H
#define CODEGEN_H

#include "parser.h"
#include "symtab.h"

#include <inttypes.h>
#include "common_types.h"

struct CodeGenerator {
    int symbolStackDepth;
    struct SymTab** symbolStack;
    struct Parser* parser;

    /* Maps math operators to their relavent operations */
    struct Map* OpImmMap;
    struct Map* OpABMap;

    int codeSize;
    byte* currentStatementCode; //Code generated by current statement
};

struct CodeGenerator* newCodeGenerator(char* filename);
void deleteCodeGenerator(struct CodeGenerator* cg);
void compileCurrentStatement(struct CodeGenerator* cg);

#endif