#ifndef CODEGEN_H
#define CODEGEN_H

#include "parser.h"
#include "symtab.h"

#include <inttypes.h>

typedef uint8_t byte;

struct CodeGenerator {
    int symbolStackDepth;
    struct SymTab** symbolStack;
    struct Parser* parser;
    byte* currentStatementCode; //Code generated by current statement
};

struct CodeGenerator* newCodeGenerator(char* filename);
void deleteCodeGenerator(struct CodeGenerator* cg);
void compileCurrentStatement(struct CodeGenerator* cg);

#endif